name: Workflow Run
on:
    workflow_run:
        workflows: [Repository Events]
        types: [completed]
jobs:
    echo-string:
        runs-on: ubuntu-latest
        steps:
            - name: print string
              run:  echo "I was ran because Repository events completed"